"""
reference_checks.py

Independent "ground truth" calculators the agent cross-checks its
LLM-generated SQL answers against, for a handful of common question
shapes. These are NOT generated by the LLM -- they're plain Python/SQL
written once, by hand, against the documented mart definitions.

This is the "explain how you verified an answer, not just how you
produced one" piece of the agent. If the agent's SQL answer disagrees
with the reference beyond a small tolerance, we flag it rather than
silently returning the (possibly wrong) number.
"""

import re
from dataclasses import dataclass
from typing import Callable, Optional

import duckdb

DB_PATH = "/tmp/subscribestack/warehouse.duckdb"
TOLERANCE_PCT = 0.5  # percent difference allowed before flagging a mismatch


@dataclass
class ReferenceCheck:
    name: str
    matches: Callable[[str], Optional[dict]]
    compute: Callable[[dict], float]
    description: str


def _month_pattern(question: str):
    """Very small heuristic matcher for '<Month> <Year>' in a question."""
    m = re.search(
        r"(January|February|March|April|May|June|July|August|September|"
        r"October|November|December)\s+(\d{4})",
        question,
        re.IGNORECASE,
    )
    if not m:
        return None
    month_name, year = m.group(1), int(m.group(2))
    months = [
        "january", "february", "march", "april", "may", "june",
        "july", "august", "september", "october", "november", "december",
    ]
    month_num = months.index(month_name.lower()) + 1
    return {"year": year, "month": month_num}


def _ref_countable_trials(params: dict) -> float:
    con = duckdb.connect(DB_PATH, read_only=True)
    result = con.execute(
        """
        select count(*) from main.fct_trials
        where is_countable_trial
          and extract(year from trial_start_date) = ?
          and extract(month from trial_start_date) = ?
        """,
        [params["year"], params["month"]],
    ).fetchone()[0]
    con.close()
    return float(result)


def _ref_conversion_rate(params: dict) -> float:
    con = duckdb.connect(DB_PATH, read_only=True)
    row = con.execute(
        """
        select
            sum(case when converted then 1 else 0 end) as conversions,
            sum(case when is_countable_trial then 1 else 0 end) as countable_trials
        from main.fct_trials
        where extract(year from trial_start_date) = ?
          and extract(month from trial_start_date) = ?
        """,
        [params["year"], params["month"]],
    ).fetchone()
    con.close()
    conversions, countable = row
    if not countable:
        return 0.0
    return round(100.0 * conversions / countable, 2)


def _ref_realized_revenue(params: dict) -> float:
    con = duckdb.connect(DB_PATH, read_only=True)
    result = con.execute(
        """
        select round(sum(realized_revenue), 2) from main.fct_revenue_daily
        where extract(year from date) = ? and extract(month from date) = ?
        """,
        [params["year"], params["month"]],
    ).fetchone()[0]
    con.close()
    return float(result or 0)


REFERENCE_CHECKS = [
    ReferenceCheck(
        name="countable_trials_by_month",
        matches=lambda q: _month_pattern(q)
        if ("trial" in q.lower() and ("how many" in q.lower() or "count" in q.lower()))
        else None,
        compute=_ref_countable_trials,
        description="Countable trial starts (excludes same-day cancels) for the given month.",
    ),
    ReferenceCheck(
        name="conversion_rate_by_month",
        matches=lambda q: _month_pattern(q)
        if ("conversion" in q.lower() or "convert" in q.lower())
        else None,
        compute=_ref_conversion_rate,
        description="Trial-to-paid conversion rate (%) for the given month.",
    ),
    ReferenceCheck(
        name="realized_revenue_by_month",
        matches=lambda q: _month_pattern(q)
        if ("realized" in q.lower() and "revenue" in q.lower())
        else None,
        compute=_ref_realized_revenue,
        description="Realized revenue (net of refunds/chargebacks/fees) for the given month.",
    ),
]


def find_reference_check(question: str):
    for check in REFERENCE_CHECKS:
        params = check.matches(question)
        if params is not None:
            return check, params
    return None, None


def verify(question: str, agent_answer: float):
    """
    Returns a dict describing how (or whether) the agent's numeric answer
    was independently verified.
    """
    check, params = find_reference_check(question)
    if check is None:
        return {
            "verified": None,
            "method": "no_reference_available",
            "note": (
                "This question doesn't match any of the reference checks this "
                "agent currently has (trial counts, conversion rate, realized "
                "revenue, all by month). Treat the answer as unverified -- "
                "spot-check it manually before using it in a decision."
            ),
        }

    reference_value = check.compute(params)
    if agent_answer is None:
        return {
            "verified": False,
            "method": check.name,
            "reference_value": reference_value,
            "note": "Agent returned no numeric answer to compare.",
        }

    if reference_value == 0:
        pct_diff = 0.0 if agent_answer == 0 else 100.0
    else:
        pct_diff = abs(agent_answer - reference_value) / abs(reference_value) * 100

    ok = pct_diff <= TOLERANCE_PCT
    return {
        "verified": ok,
        "method": check.name,
        "reference_value": reference_value,
        "agent_value": agent_answer,
        "pct_diff": round(pct_diff, 2),
        "note": (
            f"Cross-checked against an independent reference query "
            f"({check.description}). "
            + (
                "Agent's answer matches within tolerance."
                if ok
                else "MISMATCH: agent's answer deviates from the reference "
                "query beyond tolerance -- likely queried the wrong table "
                "or skipped a documented filter (e.g. is_countable_trial)."
            )
        ),
    }
